## Assignment - 6 5/4/24

## Text Summarization

In [35]:
from nltk.corpus import stopwords #you can remove stop words for speed
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

## Open file and split into sentences

In [36]:
file = open("GermanText.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Es war einmal: So fangen Märchen an
Ein Märchen ist eine sehr alte Geschichte
Dieses Märchen heißt: Schnee·wittchen
Das Märchen geht so: Auf dem Bild ist Schnee·wittchen
Schnee·wittchen ist sehr schön: Schnee·wittchen hat schwarze Haare
Und rote Lippen
Und ihre Haut ist so weiß wie Schnee
Deshalb bekommt Schnee·wittchen diesen Namen
Ein König und eine Königin leben in einem Schloss
Die Königin bekommt eine Tochter
Die Tochter ist sehr schön: Die Tochter hat schwarze Haare
Und rote Lippen
Und ihre Haut ist so weiß wie Schnee
Deshalb bekommt die Tochter den Namen: Schnee·wittchen
 Schnee·wittchen ist nur wenige Tage alt
Da stirbt die Königin
Die Geburt war nämlich sehr schwer
Ein Jahr vergeht
Da heiratet der König eine neue Frau
Die neue Frau ist jetzt die Königin
 Die neue Königin ist schön
 Und auf ihre Schönheit ist die neue Königin sehr stolz




## Our data: a list of sentences

In [37]:
print("Sentences are ", sentences)

Sentences are  [['\ufeffEs', 'war', 'einmal:', 'So', 'fangen', 'Märchen', 'an'], ['Ein', 'Märchen', 'ist', 'eine', 'sehr', 'alte', 'Geschichte'], ['Dieses', 'Märchen', 'heißt:', 'Schnee·wittchen'], ['Das', 'Märchen', 'geht', 'so:', 'Auf', 'dem', 'Bild', 'ist', 'Schnee·wittchen'], ['Schnee·wittchen', 'ist', 'sehr', 'schön:', 'Schnee·wittchen', 'hat', 'schwarze', 'Haare'], ['Und', 'rote', 'Lippen'], ['Und', 'ihre', 'Haut', 'ist', 'so', 'weiß', 'wie', 'Schnee'], ['Deshalb', 'bekommt', 'Schnee·wittchen', 'diesen', 'Namen'], ['Ein', 'König', 'und', 'eine', 'Königin', 'leben', 'in', 'einem', 'Schloss'], ['Die', 'Königin', 'bekommt', 'eine', 'Tochter'], ['Die', 'Tochter', 'ist', 'sehr', 'schön:', 'Die', 'Tochter', 'hat', 'schwarze', 'Haare'], ['Und', 'rote', 'Lippen'], ['Und', 'ihre', 'Haut', 'ist', 'so', 'weiß', 'wie', 'Schnee'], ['Deshalb', 'bekommt', 'die', 'Tochter', 'den', 'Namen:', 'Schnee·wittchen'], ['', 'Schnee·wittchen', 'ist', 'nur', 'wenige', 'Tage', 'alt'], ['Da', 'stirbt', 'die'

## Function to calculate similarity

In [38]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    for w in sent1:
        vector1[all_words.index(w)] += 1
        for w in sent2:
            vector2[all_words.index(w)] += 1
            return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [39]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Similarity matrix:\n", similarity_matrix)

Similarity matrix:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 

## Get the pagerank scores

In [40]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.008000260969636694, 1: 0.05333326084176758, 2: 0.008000260969636694, 3: 0.008000260969636694, 4: 0.008000260969636694, 5: 0.053333260841767566, 6: 0.053333260841767566, 7: 0.05333326084176758, 8: 0.05333326084176758, 9: 0.053333260841767566, 10: 0.053333260841767566, 11: 0.053333260841767566, 12: 0.053333260841767566, 13: 0.05333326084176758, 14: 0.05333326084176758, 15: 0.05333326084176758, 16: 0.053333260841767566, 17: 0.05333326084176758, 18: 0.05333326084176758, 19: 0.053333260841767566, 20: 0.05333326084176758, 21: 0.05333326084176758, 22: 0.008000260969636694}


## Sort sentences by pagerank

In [41]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.05333326084176758, ['Ein', 'Märchen', 'ist', 'eine', 'sehr', 'alte', 'Geschichte']), (0.05333326084176758, ['Ein', 'König', 'und', 'eine', 'Königin', 'leben', 'in', 'einem', 'Schloss']), (0.05333326084176758, ['Ein', 'Jahr', 'vergeht']), (0.05333326084176758, ['Deshalb', 'bekommt', 'die', 'Tochter', 'den', 'Namen:', 'Schnee·wittchen']), (0.05333326084176758, ['Deshalb', 'bekommt', 'Schnee·wittchen', 'diesen', 'Namen']), (0.05333326084176758, ['Da', 'stirbt', 'die', 'Königin']), (0.05333326084176758, ['Da', 'heiratet', 'der', 'König', 'eine', 'neue', 'Frau']), (0.05333326084176758, ['', 'Und', 'auf', 'ihre', 'Schönheit', 'ist', 'die', 'neue', 'Königin', 'sehr', 'stolz']), (0.05333326084176758, ['', 'Schnee·wittchen', 'ist', 'nur', 'wenige', 'Tage', 'alt']), (0.05333326084176758, ['', 'Die', 'neue', 'Königin', 'ist', 'schön']), (0.053333260841767566, ['Und', 'rote', 'Lippen']), (0.053333260841767566, ['Und', 'rote', 'Lippen']), (0.053333260

## Pick the top “n” sentences

In [42]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  2


## Finish off by printing summary

In [43]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Ein Märchen ist eine sehr alte Geschichte. Ein König und eine Königin leben in einem Schloss


## Language 2 

## Open file and split into sentences

In [44]:
file = open("RussianText.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

Не́которые иностра́нцы ду́мают, что в Росси́и медве́ди хо́дят по у́лицам
Коне́чно, э́то непра́вда! Медве́ди живу́т в лесу́ и не лю́бят люде́й
Встре́ча с медве́дем мо́жет быть о́чень опа́сна
Ру́сские лю́ди лю́бят ходи́ть в лес и собира́ть грибы́ и я́годы
Они́ де́лают э́то с осторо́жностью, так как медве́ди то́же о́чень лю́бят я́годы и мо́гут напа́сть на челове́ка
Медве́дь ест всё: я́годы, ры́бу, мя́со и да́же насеко́мых
Осо́бенно он лю́бит мёд
Зимо́й медве́ди обы́чно спят, потому́ что пого́да сли́шком холо́дная и нет еды́
Пока́ медве́дь спит, он мо́жет похуде́ть на 80 (во́семьдесят) килогра́мм! Ру́сские лю́ди о́чень похо́жи на медве́дей
Зимо́й они́ то́же стано́вятся медли́тельными и мно́го спят, потому́ что на у́лице сли́шком хо́лодно и темно́
Поэ́тому ру́сские лю́бят медве́дей и называ́ют их "ми́шки"
Ми́ша - э́то талисма́н ле́тней олимпиа́ды 1980 (ты́сяча девятьсо́т восьмидеся́того) го́да в Москве́
Холо́дная зима́
Медве́дь бро́дит по́ лесу, иногда́ остана́вливается, стучи́т голово́й о 

## Our data: a list of sentences

In [45]:
print("Sentences are ", sentences)

Sentences are  [['\ufeffНе́которые', 'иностра́нцы', 'ду́мают,', 'что', 'в', 'Росси́и', 'медве́ди', 'хо́дят', 'по', 'у́лицам'], ['Коне́чно,', 'э́то', 'непра́вда!', 'Медве́ди', 'живу́т', 'в', 'лесу́', 'и', 'не', 'лю́бят', 'люде́й'], ['Встре́ча', 'с', 'медве́дем', 'мо́жет', 'быть', 'о́чень', 'опа́сна'], ['Ру́сские', 'лю́ди', 'лю́бят', 'ходи́ть', 'в', 'лес', 'и', 'собира́ть', 'грибы́', 'и', 'я́годы'], ['Они́', 'де́лают', 'э́то', 'с', 'осторо́жностью,', 'так', 'как', 'медве́ди', 'то́же', 'о́чень', 'лю́бят', 'я́годы', 'и', 'мо́гут', 'напа́сть', 'на', 'челове́ка'], ['Медве́дь', 'ест', 'всё:', 'я́годы,', 'ры́бу,', 'мя́со', 'и', 'да́же', 'насеко́мых'], ['Осо́бенно', 'он', 'лю́бит', 'мёд'], ['Зимо́й', 'медве́ди', 'обы́чно', 'спят,', 'потому́', 'что', 'пого́да', 'сли́шком', 'холо́дная', 'и', 'нет', 'еды́'], ['Пока́', 'медве́дь', 'спит,', 'он', 'мо́жет', 'похуде́ть', 'на', '80', '(во́семьдесят)', 'килогра́мм!', 'Ру́сские', 'лю́ди', 'о́чень', 'похо́жи', 'на', 'медве́дей'], ['Зимо́й', 'они́', 'то́же

## Function to calculate similarity

In [46]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    for w in sent1:
        vector1[all_words.index(w)] += 1
        for w in sent2:
            vector2[all_words.index(w)] += 1
            return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [47]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Similarity matrix:\n", similarity_matrix)

Similarity matrix:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Get the pagerank scores

In [48]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.027273481301247175, 1: 0.027273481301247175, 2: 0.027273481301247175, 3: 0.027273481301247175, 4: 0.027273481301247175, 5: 0.1818162967468819, 6: 0.027273481301247175, 7: 0.1818162967468819, 8: 0.027273481301247175, 9: 0.1818162967468819, 10: 0.027273481301247175, 11: 0.027273481301247175, 12: 0.027273481301247175, 13: 0.1818162967468819}


## Sort sentences by pagerank

In [49]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.1818162967468819, ['Медве́дь', 'ест', 'всё:', 'я́годы,', 'ры́бу,', 'мя́со', 'и', 'да́же', 'насеко́мых']), (0.1818162967468819, ['Медве́дь', 'бро́дит', 'по́', 'лесу,', 'иногда́', 'остана́вливается,', 'стучи́т', 'голово́й', 'о', 'де́рево', 'и', 'кричи́т:', '"Ну', 'заче́м,', 'заче́м', 'я', 'пил', 'сто́лько', 'ко́фе!?"']), (0.1818162967468819, ['Зимо́й', 'они́', 'то́же', 'стано́вятся', 'медли́тельными', 'и', 'мно́го', 'спят,', 'потому́', 'что', 'на', 'у́лице', 'сли́шком', 'хо́лодно', 'и', 'темно́']), (0.1818162967468819, ['Зимо́й', 'медве́ди', 'обы́чно', 'спят,', 'потому́', 'что', 'пого́да', 'сли́шком', 'холо́дная', 'и', 'нет', 'еды́']), (0.027273481301247175, ['\ufeffНе́которые', 'иностра́нцы', 'ду́мают,', 'что', 'в', 'Росси́и', 'медве́ди', 'хо́дят', 'по', 'у́лицам']), (0.027273481301247175, ['Холо́дная', 'зима́']), (0.027273481301247175, ['Ру́сские', 'лю́ди', 'лю́бят', 'ходи́ть', 'в', 'лес', 'и', 'собира́ть', 'грибы́', 'и', 'я́годы']), (0.0

## Pick the top “n” sentences

In [50]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  4


## Finish off by printing summary

In [51]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 Медве́дь ест всё: я́годы, ры́бу, мя́со и да́же насеко́мых. Медве́дь бро́дит по́ лесу, иногда́ остана́вливается, стучи́т голово́й о де́рево и кричи́т: "Ну заче́м, заче́м я пил сто́лько ко́фе!?". Зимо́й они́ то́же стано́вятся медли́тельными и мно́го спят, потому́ что на у́лице сли́шком хо́лодно и темно́. Зимо́й медве́ди обы́чно спят, потому́ что пого́да сли́шком холо́дная и нет еды́


## Language 3

## Open file and split into sentences

In [52]:
file = open("SpanishText.txt", "r")
#This file contains one paragraph of multiple sentences
filedata = file.readlines()
article = filedata[0].split(". ") #Just do the first paragraph
sentences = []
for sentence in article:
    print(sentence)
    sentences.append(sentence.replace("[^a-zA-Z]", " ").split(" "))

En el año 1492 (mil cuatrocientos noventa y dos), la isla de Puerto Rico era un paraíso tropical
La isla se llamaba Borinquén y sus habitantes eran los Taínos
Aunque a veces sufrían ataques de sus vecinos, los Caribes, en general, había paz en la isla
No sabían que sus vidas estaban a punto de cambiar drásticamente
En su segundo viaje al Nuevo Mundo, Cristóbal Colón visitó Borinquén el 19 (diecinueve) de noviembre de 1493 (mil cuatrocientos noventa y tres)
Nombró la isla “San Juan Bautista”
España no estableció un pueblo en la isla hasta 1508 (mil quinientos ocho)
La colonia se llamaba Puerto Rico
En la década 1520 (mil quinientos veinte), cambiaron los nombres de la colonia y la isla
Ahora, la ciudad se llamaba San Juan y la isla se llamaba Puerto Rico
Y sus habitantes originales, los taínos, eran prácticamente extintos
En 1860 (mil ochocientos sesenta), Puerto Rico y Cuba eran las últimas colonias de España en América, y ellos también querían su independencia
La situación en Puerto R

## Our data: a list of sentences

In [53]:
print("Sentences are ", sentences)

Sentences are  [['\ufeffEn', 'el', 'año', '1492', '(mil', 'cuatrocientos', 'noventa', 'y', 'dos),', 'la', 'isla', 'de', 'Puerto', 'Rico', 'era', 'un', 'paraíso', 'tropical'], ['La', 'isla', 'se', 'llamaba', 'Borinquén', 'y', 'sus', 'habitantes', 'eran', 'los', 'Taínos'], ['Aunque', 'a', 'veces', 'sufrían', 'ataques', 'de', 'sus', 'vecinos,', 'los', 'Caribes,', 'en', 'general,', 'había', 'paz', 'en', 'la', 'isla'], ['No', 'sabían', 'que', 'sus', 'vidas', 'estaban', 'a', 'punto', 'de', 'cambiar', 'drásticamente'], ['En', 'su', 'segundo', 'viaje', 'al', 'Nuevo', 'Mundo,', 'Cristóbal', 'Colón', 'visitó', 'Borinquén', 'el', '19', '(diecinueve)', 'de', 'noviembre', 'de', '1493', '(mil', 'cuatrocientos', 'noventa', 'y', 'tres)'], ['Nombró', 'la', 'isla', '“San', 'Juan', 'Bautista”'], ['España', 'no', 'estableció', 'un', 'pueblo', 'en', 'la', 'isla', 'hasta', '1508', '(mil', 'quinientos', 'ocho)'], ['La', 'colonia', 'se', 'llamaba', 'Puerto', 'Rico'], ['En', 'la', 'década', '1520', '(mil', 'qu

## Function to calculate similarity

In [54]:
def sentence_similarity(sent1, sent2 ):
    sent1 = [w.lower() for w in sent1]
    sent2 = [w.lower() for w in sent2]
    all_words = list(set(sent1 + sent2))
    vector1 = [0] * len(all_words)
    vector2 = [0] * len(all_words)
    for w in sent1:
        vector1[all_words.index(w)] += 1
        for w in sent2:
            vector2[all_words.index(w)] += 1
            return 1 - cosine_distance(vector1, vector2)

## Create the similarity matrix

In [55]:
similarity_matrix = np.zeros((len(sentences), len(sentences)))

for idx1 in range(len(sentences)):
    for idx2 in range(len(sentences)):
        if idx1 == idx2: #ignore if both are same sentences
            continue
        similarity_matrix[idx1][idx2] = sentence_similarity(sentences[idx1], sentences[idx2])

print("Similarity matrix:\n", similarity_matrix)

Similarity matrix:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

## Get the pagerank scores

In [56]:
# Step 3 - Rank sentences in similarity martix
sentence_similarity_graph = nx.from_numpy_array(similarity_matrix)
scores = nx.pagerank(sentence_similarity_graph)
print("scores", scores)

scores {0: 0.009231348331386034, 1: 0.061537841073514975, 2: 0.009231348331386034, 3: 0.06153784107351499, 4: 0.06153784107351499, 5: 0.009231348331386034, 6: 0.009231348331386034, 7: 0.061537841073514975, 8: 0.06153784107351499, 9: 0.009231348331386034, 10: 0.009231348331386034, 11: 0.06153784107351499, 12: 0.061537841073514975, 13: 0.061537841073514975, 14: 0.061537841073514975, 15: 0.061537841073514975, 16: 0.009231348331386034, 17: 0.06153784107351499, 18: 0.009231348331386034, 19: 0.06153784107351499, 20: 0.009231348331386034, 21: 0.06153784107351499, 22: 0.009231348331386034, 23: 0.009231348331386034, 24: 0.061537841073514975, 25: 0.009231348331386034, 26: 0.009231348331386034, 27: 0.009231348331386034, 28: 0.009231348331386034}


## Sort sentences by pagerank

In [57]:
# Step 4 - Sort the rank and pick top sentences
ranked_sentence = sorted(((scores[i],s) for i,s in
enumerate(sentences)), reverse=True)
print("Indexes of top ranked_sentence order are \n\n",
ranked_sentence)

Indexes of top ranked_sentence order are 

 [(0.06153784107351499, ['No', 'sabían', 'que', 'sus', 'vidas', 'estaban', 'a', 'punto', 'de', 'cambiar', 'drásticamente']), (0.06153784107351499, ['No', 'fue', 'una', 'independencia', 'total,', 'pero', 'permitió', 'elecciones', 'locales', 'para', 'los', 'puertorriqueños']), (0.06153784107351499, ['En', 'su', 'segundo', 'viaje', 'al', 'Nuevo', 'Mundo,', 'Cristóbal', 'Colón', 'visitó', 'Borinquén', 'el', '19', '(diecinueve)', 'de', 'noviembre', 'de', '1493', '(mil', 'cuatrocientos', 'noventa', 'y', 'tres)']), (0.06153784107351499, ['En', 'la', 'década', '1520', '(mil', 'quinientos', 'veinte),', 'cambiaron', 'los', 'nombres', 'de', 'la', 'colonia', 'y', 'la', 'isla']), (0.06153784107351499, ['En', '1860', '(mil', 'ochocientos', 'sesenta),', 'Puerto', 'Rico', 'y', 'Cuba', 'eran', 'las', 'últimas', 'colonias', 'de', 'España', 'en', 'América,', 'y', 'ellos', 'también', 'querían', 'su', 'independencia']), (0.06153784107351499, ['Cuba', 'tenía', 'gra

## Pick the top “n” sentences

In [58]:
#Step 5 - How many sentences to pick
n = int(input("How many sentences do you want in the summary? "))
#n=2
summarize_text = []
for i in range(n):
    summarize_text.append(" ".join(ranked_sentence[i][1]))

How many sentences do you want in the summary?  5


## Finish off by printing summary

In [59]:
# Step 6 - Offcourse, output the summarize text
print("Summarize Text: \n", ". ".join(summarize_text))

Summarize Text: 
 No sabían que sus vidas estaban a punto de cambiar drásticamente. No fue una independencia total, pero permitió elecciones locales para los puertorriqueños. En su segundo viaje al Nuevo Mundo, Cristóbal Colón visitó Borinquén el 19 (diecinueve) de noviembre de 1493 (mil cuatrocientos noventa y tres). En la década 1520 (mil quinientos veinte), cambiaron los nombres de la colonia y la isla. En 1860 (mil ochocientos sesenta), Puerto Rico y Cuba eran las últimas colonias de España en América, y ellos también querían su independencia
